# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ExactGen <- function(Xt, Xc, Nt, Nc, pcupper, pclower, Thetagrid, Pgrid, cov_prob, B, dev_region_num) {
    .Call(`_ExactGene_ExactGen`, Xt, Xc, Nt, Nc, pcupper, pclower, Thetagrid, Pgrid, cov_prob, B, dev_region_num)
}

individual_p_cpp <- function(xt, xc, nt, nc, pcupper, pclower, theta_grd, Pgrid, dev_region_num) {
    .Call(`_ExactGene_individual_p_cpp`, xt, xc, nt, nc, pcupper, pclower, theta_grd, Pgrid, dev_region_num)
}

